# 不同檩数的举架规则
beam_systems:
  # 四檩举架系统
  4:
    name: "四檩架"
    beam_names: ["檐檩", "脊檩"]
    step_count: 2
    lift_ratios: [0.5, 1.0]           # 檐步0.5举，脊步1.0举
    step_frame_ratios: [0.5, 0.5]     # 两步架各占50%
    description: "用于四檩卷棚等小型建筑"

  # 五檩举架系统  
  5:
    name: "五檩架"
    beam_names: ["檐檩", "金檩", "脊檩"]
    step_count: 3
    lift_ratios: [0.5, 0.7, 1.0]      # 五举、七举、十举
    step_frame_ratios: [0.4, 0.3, 0.3] # 檐步40%，金步30%，脊步30%
    description: "标准五檩举架"

  # 六檩举架系统
  6:
    name: "六檩架" 
    beam_names: ["檐檩", "下金檩", "上金檩", "脊檩"]
    step_count: 4
    lift_ratios: [0.5, 0.65, 0.8, 1.0] # 五举、六五举、八举、十举
    step_frame_ratios: [0.3, 0.25, 0.25, 0.2]
    description: "用于六檩前后廊建筑"

  # 七檩举架系统
  7:
    name: "七檩架"
    beam_names: ["檐檩", "下金檩", "中金檩", "上金檩", "脊檩"]
    step_count: 5
    lift_ratios: [0.5, 0.6, 0.7, 0.9, 1.0]
    step_frame_ratios: [0.25, 0.2, 0.2, 0.2, 0.15]
    description: "用于大型厅堂"

  # 八檩举架系统
  8:
    name: "八檩架"
    beam_names: ["檐檩", "下金檩", "中金檩", "上金檩", "脊檩"]
    step_count: 6
    lift_ratios: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    step_frame_ratios: [0.2, 0.18, 0.17, 0.17, 0.15, 0.13]
    description: "用于大型殿堂"

# 特殊举架规则
special_lift_systems:
  # 卷棚举架（屋面曲线更柔和）
  juanpeng:
    4: [0.4, 0.8]           # 四檩卷棚
    6: [0.4, 0.6, 0.8, 1.0] # 六檩卷棚
  
  # 歇山举架（山面特殊处理）
  xieshan:
    6: [0.5, 0.65, 0.75, 0.9, 1.0]