building_forms:
  # 悬山类
  "四檩悬山":
    roof_type: "xuanshan"
    structural_style: "small"
    typical_beams: 4
    allowed_corridors: ["无廊", "前廊", "后廊", "前后廊"]
    
  "四檩悬山卷棚":
    roof_type: "xuanshan_juanpeng"
    structural_style: "small" 
    typical_beams: 4
    lift_system: "juanpeng"  # 使用卷棚举架规则
    allowed_corridors: ["无廊", "前廊", "后廊", "前后廊"]

  "六檩悬山":
    roof_type: "xuanshan"
    structural_style: "small"
    typical_beams: 6
    allowed_corridors: ["无廊", "前廊", "后廊", "前后廊"]

  # 歇山类
  "一殿一卷":
    roof_type: "xieshan"
    structural_style: "small" 
    typical_beams: 6
    lift_system: "xieshan"  # 使用歇山举架规则
    allowed_corridors: ["前廊", "前后廊"]

  # 攒尖类
  "四角攒尖":
    roof_type: "sijiao_cuijian"
    structural_style: "small"
    is_pavilion: true
    # 攒尖建筑使用特殊的檩架计算