# 小式建筑比例规则
small_style:
  # 柱网计算规则
  column_network:
    # 楹数 → 开间布局
    bay_layouts:
      3: ["明间", "次间"]                    # 三楹：明间+次间×2
      5: ["明间", "次间", "次间"]            # 五楹：明间+次间×4  
      7: ["明间", "次间", "次间", "梢间"]    # 七楹：明间+次间×4+梢间×2
    
    # 开间比例规则
    bay_ratios:
      mingjian: 1.0
      cijian: 0.85
      shaojian: 0.7

  # 进深计算规则
  depth_system:
    # 根据檐步架和檩数计算总进深
    total_depth_formula: "eave_step * (beam_count - 1)"
    
    # 廊子进深
    corridor_depth: "eave_height * 0.8"

# 小式建筑构件比例（基于柱径）
small_style_components:
  # 柱类规则
  pillars:
    eave_column:
      diameter_formula: "bay_width * 0.077"  # 柱径 ≈ 面阔 × 1/13
      height_formula: "diameter * 11"        # 柱高 ≈ 柱径 × 11
      
    corner_column:
      diameter_formula: "eave_diameter * 1.1"
      height_formula: "eave_height * 1.02"
      has_ce_jiao: true

  # 梁类规则  
  beams:
    beam_height_ratio: 1.2    # 梁高 = 柱径 × 1.2
    beam_width_ratio: 0.8     # 梁宽 = 柱径 × 0.8
    
  # 檩类规则
  purlins:
    diameter_ratio: 0.9       # 檩径 ≈ 柱径 × 0.9

# 廊系统规则
corridor_systems:
  无廊:
    has_corridor: false
    
  前廊:
    corridor_width: "eave_height * 0.8"
    corridor_columns: 1
    
  后廊:
    corridor_width: "eave_height * 0.8" 
    corridor_columns: 1
    
  前后廊:
    corridor_width: "eave_height * 0.8"
    corridor_columns: 2