[system]
version = "1.0.0"


[default]
units = "meters"
scale = 1
segments = 16


# 精度相关的生成选项
[options]
auto_lod = true            # 是否自动根据距离调整细节层次
memory_optimization = true # 是否启用内存优化

[debug]
log_level = "info"
enable_validation = true
