# 建筑主要类别
[building_categories]
building = { name = "房屋建筑", description = "主要的居住和使用建筑" }
gate = { name = "门类建筑", description = "各种类型的门建筑" }
corridor = { name = "廊类建筑", description = "连接和交通功能的廊建筑" }
pavilion = { name = "亭类建筑", description = "亭、榭等点景建筑" }

# 屋顶形式
[roof_forms]
hard_hill = "硬山"
hanging_hill = "悬山"
hip_roof = "歇山"
hip_roof_palace = "庑殿"
pyramidal_roof = "攒尖"


# 建筑等级
[construction_grades]
grade_1 = {}                                # 大式一等建筑构件参数斗口制
grade_2 = { diameter = 0.1, height = 1.0 }  # 大式无斗拱檐柱径制
grade_3 = { diameter = 0.07, height = 0.8 } # 小式檐柱径制


# 屋脊类型
[ridge_types]
main_ridge = "大屋脊"
roll_shed = "卷棚"

# 出廊
[corridor_types]
front_corridor = true

# 通则
[general_rules]

# 收分
[general_rules.tilted]


# 出水回水
[general_rules.overhang]

# 举架
[general_rules.lift_height]
4 = [0.5, 0.5]


# 第三节 权衡
[components_small_style]

[components_small_style.pillar_delta] # 檐柱径增量
pillar_gold = 0.1
pillar_middle = 0.03
pillar_mountain = 0.03

[components_small_style.beam_specs]
beam_embracing_head = ["D", 0.25, 4.2] # 长宽高,长为檐步架加D


beam_specs = { baotouliang = [0.18, 0.25, 4.2] }


# 建筑形式
[building_forms]

# 六檩卷棚大式
[building_forms."六檩卷棚大式"]
name = "six_purlin_roll_shed_large"
construction_grade = "grade_2"
is_pillar_eave = true

# 四檩卷棚小式
[building_forms."四檩卷棚小式"]
name = "four_purlin_roll_shed_small"
construction_grade = "grade_3"
is_pillar_eave = true
