# 柱子类型
[pillars]
eave_column = { name = "檐柱", diameter_ratio = 0.077, height_ratio = 11.0 }
corner_column = { name = "角柱", diameter_ratio = 0.085, height_ratio = 11.2 }
gold_column = { name = "金柱", diameter_ratio = 0.085, height_ratio = 12.0 }
melon_column = { name = "瓜柱", diameter_ratio = 0.07, height_ratio = "dynamic" }
hanging_columns = { name = "垂莲柱", diameter_ratio = 0.06, height_ratio = 0.8 }

# 梁类型
[beams]
five_purlin_beam = { name = "五架梁", height_ratio = 1.5, width_ratio = 1.2 }
three_purlin_beam = { name = "三架梁", height_ratio = 1.2, width_ratio = 1.0 }
four_purlin_beam = { name = "四架梁", height_ratio = 1.3, width_ratio = 1.1 }
main_beam = { name = "麻叶抱头梁", height_ratio = 1.4, width_ratio = 1.1 }

# 檩类型
[purlins]
eave_purlin = { name = "檐檩", diameter_ratio = 0.9 }
gold_purlin = { name = "金檩", diameter_ratio = 0.85 }
ridge_purlin = { name = "脊檩", diameter_ratio = 0.8 }