[mapping]

[mapping.garden]
name = "garden"
fields = ["园林名称", "园中园编号", "园中园名称"]
naming_template = "COL_{园林名称}_{园中园编号}_{园中园名称}"

[mapping.arch]
name = "arch"
fields = ["建筑编号", "建筑名称"]
naming_template = "COL_{建筑编号}_{建筑名称}"

[mapping.arch.shape]
fields = ["建筑形式", "出廊", "楹", "描述1"]

[mapping.arch.bay]
fields = ["明间", "次间", "二次间", "三次间", "四次间"]

[mapping.arch.depth]
fields = ["通进深", "檐步架"]

[mapping.arch.height]
fields = ["标注檐柱高", "标注柱径", "标注台明高", "标注上出", "标注下出"]

[field_aliases]
"园林名称" = "garden_name"
"园中园编号" = "garden_id"
"园中园名称" = "sub_garden_name"
"建筑编号" = "building_id"
"建筑名称" = "building_name"
"建筑形式" = "building_form"
"出廊" = "corridor_type"
"楹" = "columns_count"
"描述1" = "description"
"明间" = "main_bay"
"次间" = "side_bay"
"二次间" = "secondary_side_bay"
"三次间" = "tertiary_side_bay"
"四次间" = "quaternary_side_bay"
"通进深" = "total_depth"
"檐步架" = "eave_step"
"标注檐柱高" = "annotated_column_height"
"标注柱径" = "annotated_column_diameter"
"标注台明高" = "annotated_platform_height"
"标注上出" = "annotated_upper_overhang"
"标注下出" = "annotated_lower_overhang"
