[mapping]

[mapping.garden]
name = "garden"
fields = ["园林名称", "园中园编号", "园中园名称"]
naming_template = "COL_{园林名称}_{园中园编号}_{园中园名称}"

[mapping.arch]
name = "arch"
fields = ["建筑编号", "建筑名称"]
naming_template = "COL_{建筑编号}_{建筑名称}"


[mapping.arch.bays]
fields = ["明间", "次间", "二次间", "三次间", "四次间"]

[mapping.arch.depth]
fields = ["通进深", "檐步架"]

[mapping.arch.height]
fields = ["标注檐柱高", "标注柱径", "标注台明高", "标注上出", "标注下出"]


[corridor_types]
"无廊" = "none_corridor"
"前出廊" = "front_corridor"
"前后廊" = "both_side_corridor"
"周围廊" = "surround_corridor"

[building_positions]
"正房" = "main_house"
"厢房" = "side_house"
"耳房" = "annex_house"
"倒座房" = "reversed_house"
"后罩房" = "back_house"

[field_aliases]
"园林名称" = "garden_name"
"园中园编号" = "garden_id"
"园中园名称" = "sub_garden_name"
"建筑编号" = "building_id"
"建筑名称" = "building_name"
"建筑形式" = "building_form"
"出廊" = "corridor_type"
"楹" = "columns_count"
"描述1" = "description"
"明间" = "main_bay"
"次间" = "side_bay"
"二次间" = "secondary_side_bay"
"三次间" = "tertiary_side_bay"
"梢间" = "end_bay"
"通进深" = "total_depth"
"檐步架" = "eave_step"
"标注檐柱高" = "annotated_eave_column_height"
"标注柱径" = "annotated_eave_column_diameter"
"标注台明高" = "annotated_platform_height"
"标注上出" = "annotated_upper_overhang"
"标注下出" = "annotated_lower_overhang"
