[project]
name = "古建筑术语词典"
version = "1.0"

[settings]
default_language = "chinese"


# 术语内容
[geometry]
"檐柱" = "eave-pillar"
"金柱" = "gold-pillar"
"中柱" = "center-pillar"
"山柱" = "gable-pillar"

"五架梁" = "beam-5rd"
"三架梁" = "beam-3rd"
"月梁" = "crescent-beam"

"额枋" = "architrave"
"随梁枋" = "tie-beam"


"庑殿顶" = "hipped-roof"
"歇山顶" = "hip-gable-roof"
"硬山顶" = "hard-gable-roof"
