
# 开间类型
[bays]
"明间" = "main_bay"
"次间" = "side_bay"
"二次间" = "secondary_side_bay"
"三次间" = "tertiary_side_bay"
"四次间" = "quaternary_side_bay"
"梢间" = "end_bay"

# 结构构件
[components]
"檐柱" = "eave_column"
"金柱" = "gold_column"
"角柱" = "corner_column"
"檐檩" = "eave_purlin"
"金檩" = "gold_purlin"
"脊檩" = "ridge_purlin"

# 尺寸术语
[dimensions]
"通面阔" = "total_width"
"通进深" = "total_depth"
"檐步架" = "eave_step"
"金步架" = "gold_step"
"脊步架" = "ridge_step"
"上出" = "upper_overhang"
"下出" = "lower_overhang"
