# 建筑参数配置
[building_parameters]
[building_parameters.en]
roof_pitch_range = [0.5, 0.65, 0.8] # 举高比例范围
eave_overhang_range = [0.3, 0.5]    # 出檐范围
column_diameter_range = [0.2, 0.4]  # 柱径范围

# 或者保持中文键名
[building_parameters.zh]
"举高" = [0.5, 0.65]
"出檐" = [0.3, 0.5]
"柱径" = [0.2, 0.4]
